### ISSUE TITLE
[ament_cppcheck]: CI cppcheck Fails to Analyze Files with gtest Syntax in GitHub Actions

### ISSUE THREAD

**Issue by des99w** [ament/ament_lint#517]
## Description
When running cppcheck as part of the ament_cppcheck tool in a GitHub Actions workflow, it fails to parse and analyze test files that include gtest syntax correctly. This results in syntaxError messages for lines that contain valid gtest constructs.

## Error Output
Example errors seen in the CI logs:
```bash
Error: [tests/Test.cpp:183]: (error: syntaxError) syntax error
```
## CI file

```yml
name: lint
on: 
  pull_request:
  push:

jobs:
  ament_lint:
    name: ament_${{matrix.linter}}
    runs-on: ubuntu-22.04
    container: 
      image: ubuntu:jammy
    strategy:
      fail-fast: false
      matrix:
        linter: [clang-format, cpplint, cppcheck]
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up ROS
        uses: ros-tooling/setup-ros@master
        with:
          distribution: humble

      # To allow slow cppcheck versions
      - name: Set Environment Variable for Cppcheck
        if: matrix.linter == 'cppcheck'
        run: |
          echo "AMENT_CPPCHECK_ALLOW_SLOW_VERSIONS=1" >> $GITHUB_ENV

      - name: Run ROS Linter
        uses: ros-tooling/action-ros-lint@v0.1
        with:
          linter: ${{ matrix.linter }}
          distribution: humble
          package-name: pkg_name
```

## Steps to Reproduce
Create a C++ test file using gtest (e.g., Test.cpp).
Add valid gtest constructs such as:
```cpp
TEST_F(Test, ValidScenario) {
    ASSERT_EQ(1, 1);
}
```
Configure a GitHub Actions workflow to run cppcheck with ament_cppcheck.
Could you observe that cppcheck flags syntax errors on valid gtest lines?

## Expected Behavior
cppcheck should either:

- Ignore gtest constructs when performing static analysis, or
- Correctly analyze the test files without raising syntax errors.

## Actual Behavior
cppcheck fails with syntaxError on valid gtest syntax.

## Attempts to Solve
I was trying to use `echo "AMENT_LINT_AUTO_FILE_EXCLUDE=tests/*.cpp" >> $GITHUB_ENV`, also I tried to use `--exclude tests` or `--suppress=syntaxError` as args to workaround but still.
